name: .NET Test

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"
    - name: Run C# unit tests
      run: dotnet test E4EDataManagement.Tests
