name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.DEPLOY }}


    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.8.6
      with:
        github_token: ${{ secrets.DEPLOY }}
        root_options: "-vv"
